from idautils import *
from idaapi import *
from idc import *

import string

rodata_start_addr = 0x959b0
rodata_end_addr = 0x9af68

decrypted_str = [
    "n001",
"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)V",
"n002",
"(Landroid/content/Context;)V",
"n003",
"()V",
"%s/.bdlock",
"FeatureLibcProtection",
"libc.so",
"statvfs",
"pwrite",
"pread",
"pwrite64",
"pread64",
"gettid",
"ftruncate",
"__system_property_get",
"sysconf",
"execl",
"execv",
"execve",
"write",
"flock",
"kill",
"waitpid",
"getpid",
"getppid",
"setrlimit",
"prctl",
"fork",
"bsd_signal",
"select",
"read",
"fstat",
"lseek",
"munmap",
"mmap",
"closedir",
"readdir",
"opendir",
"pthread_self",
"pthread_detach",
"strncmp",
"strchr",
"snprintf",
"time",
"stat",
"unlink",
"close",
"open",
"mkdir",
"utime",
"strcasecmp",
"strcmp",
"strdup",
"free",
"sscanf",
"strlen",
"mprotect",
"ptrace",
"strstr",
"strtoull",
"strtoul",
"fgets",
"fclose",
"fopen",
"memset",
"calloc",
"malloc",
"memcpy",
"pthread_join",
"pthread_create",
"exit",
"_exit",
"FeatureProtectClassLoader",
"android/app/ActivityThread",
"android/app/LoadedApk",
"android/util/ArrayMap",
"java/lang/ref/WeakReference",
"java/lang/ClassLoader",
"currentActivityThread",
"()Landroid/app/ActivityThread;",
"mPackages",
"Landroid/util/ArrayMap;",
"get",
"(Ljava/lang/Object;)Ljava/lang/Object;",
"get",
"()Ljava/lang/Object;",
"mClassLoader",
"Ljava/lang/ClassLoader;",
"parent",
"Ljava/lang/ClassLoader;",
"dalvik/system/InMemoryDexClassLoader",
"<init>",
"(Ljava/nio/ByteBuffer;Ljava/lang/ClassLoader;)V",
"dalvik/system/BaseDexClassLoader",
"dalvik/system/DexPathList",
"pathList",
"Ldalvik/system/DexPathList;",
"dexElements",
"[Ldalvik/system/DexPathList$Element;",
"dalvik/system/DexPathList$Element",
"dalvik/system/DexPathList",
"pathList",
"Ldalvik/system/DexPathList;",
"dexElements",
"[Ldalvik/system/DexPathList$Element;",
"dalvik/system/DexPathList$Element",
"dalvik/system/DexPathList",
"pathList",
"Ldalvik/system/DexPathList;",
"dexElements",
"[Ldalvik/system/DexPathList$Element;",
"dalvik/system/DexPathList$Element",
"dalvik/system/PathClassLoader",
"dalvik/system/DexClassLoader",
"mPaths",
"[Ljava/lang/String;",
"mRawDexPath",
"Ljava/lang/String;",
"java/lang/String",
"mFiles",
"[Ljava/io/File;",
"mFiles",
"[Ljava/io/File;",
"mZips",
"[Ljava/util/zip/ZipFile;",
"mZips",
"[Ljava/util/zip/ZipFile;",
"mDexs",
"[Ldalvik/system/DexFile;",
"mDexs",
"[Ldalvik/system/DexFile;",
"java/io/File",
"java/util/zip/ZipFile",
"dalvik/system/DexFile",
"findClass",
"(Ljava/lang/String;)Ljava/lang/Class;",
"bbbbbbbb1",
"dalvik/system/DexClassLoader",
"android/app/ActivityThread",
"android/app/LoadedApk",
"android/util/ArrayMap",
"java/lang/ref/WeakReference",
"java/lang/ClassLoader",
"currentActivityThread",
"()Landroid/app/ActivityThread;",
"mPackages",
"Landroid/util/ArrayMap;",
"get",
"(Ljava/lang/Object;)Ljava/lang/Object;",
"get",
"()Ljava/lang/Object;",
"mClassLoader",
"Ljava/lang/ClassLoader;",
"parent",
"Ljava/lang/ClassLoader;",
"<init>",
"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)V",
"java/lang/Class",
"getDex",
"()Lcom/android/dex/Dex;",
"bbbbbbbb%d",
"dalvik/system/DexClassLoader",
"android/app/ActivityThread",
"android/app/LoadedApk",
"java/util/HashMap",
"java/lang/ref/WeakReference",
"java/lang/ClassLoader",
"currentActivityThread",
"()Landroid/app/ActivityThread;",
"mPackages",
"Ljava/util/HashMap;",
"get",
"(Ljava/lang/Object;)Ljava/lang/Object;",
"get",
"()Ljava/lang/Object;",
"mClassLoader",
"Ljava/lang/ClassLoader;",
"parent",
"Ljava/lang/ClassLoader;",
"<init>",
"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)V",
"dalvik/system/DexClassLoader",
"android/app/ActivityThread",
"android/app/ActivityThread$PackageInfo",
"java/util/HashMap",
"java/lang/ref/WeakReference",
"java/lang/ClassLoader",
"currentActivityThread",
"()Landroid/app/ActivityThread;",
"mPackages",
"Ljava/util/HashMap;",
"get",
"(Ljava/lang/Object;)Ljava/lang/Object;",
"get",
"()Ljava/lang/Object;",
"mClassLoader",
"Ljava/lang/ClassLoader;",
"parent",
"Ljava/lang/ClassLoader;",
"<init>",
"(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)V",
"",
"%02x",
"%s",
"android/content/pm/Signature",
"android/content/pm/PackageInfo",
"android/content/pm/PackageManager",
"android/app/ActivityThread",
"android/app/ContextImpl",
"getSystemContext",
"()Landroid/app/ContextImpl;",
"currentActivityThread",
"()Landroid/app/ActivityThread;",
"getPackageManager",
"()Landroid/content/pm/PackageManager;",
"getPackageInfo",
"(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;",
"signatures",
"[Landroid/content/pm/Signature;",
"toByteArray",
"()[B",
"android/os/Build$VERSION",
"SDK_INT",
"I",
"%s",
"[%s:%u]:%s",
"libaoc.so",
"libart.so",
"__android_log_print",
"open",
"close",
"mmap",
"execl",
"execv",
"execv",
"execve",
"memcpy",
"ExtractToMemory",
"open",
"close",
"mmap",
"execl",
"execv",
"execv",
"execve",
"memcpy",
"ExtractToMemory",
"--dex-file=",
"--dex-file=",
"libaoc.so",
"libartbase.so",
"libart.so",
"__android_log_print",
"mmap",
"mmap",
"open",
"mmap",
"munmap",
"close",
"execv",
"mprotect",
"/system/lib/libvmkid_lemur.so",
"libdvm.so",
"libvmkid_lemur.so",
"libdvm.so",
"open",
"mmap",
"munmap",
"close",
"execv",
"execv",
"mprotect",
"__android_log_print",
"dexopt",
"%s",
"/data/dalvik-cache/%s@classes.dex",
"dexopt",
"0",
"valgrind",
"0",
"assets/baiduprotect%d.jar",
"assets/baiduprotect%d.jar",
"assets/baiduprotect%d.i",
"assets/baiduprotect%d.jar",
"/data/data/",
"/data/data/",
"/data/user/%u/%s",
"/data/user/%u/",
"/data/data/",
"android/os/Build",
"MODEL",
"Ljava/lang/String;",
"%s/lib",
"%s/.%d",
"assets/baiduprotect%d.jar",
"/1.jar",
"/classes.jar",
"/classes.dex",
"/data/data/%s/.%d/classes.jar",
"/data/data/%s/.%d/classes.dex",
"android/os/Build",
"FINGERPRINT",
"Ljava/lang/String;",
"%s/.1/.config",
"FeatureProtectEnvironment",
"com/baidu/protect/A",
"unknown",
"FeatureGlobalInfo",
"arm64-v8a",
"/proc/self/maps",
"r",
"FeatureIntegrityCheck",
"[%s:%u]:%s",
"assets/baiduprotect.m",
"%s",
"classes.dex",
"classes%d.dex",
"/proc/self/maps",
"r",
"r--p",
"%s %s %*s %*s %*s %s",
"r-xp",
"com/baidu/protect/CrashHandler",
"com/baidu/protect/B",
"com/baidu/protect/AppInfo",
"c07954f5209e7c14",
"f8547c5c1b4a426b",
"f8547c5c1b4a426b8db3ad940a4aa415",
"359b71797ac5dbcc07954f5209e7c146",
".suuid",
"FeatureReportCrash",
"asynRun",
"()V",
"asynRun",
"()V",
"com/baidu/protect/B",
"buildUUID",
"()Ljava/lang/String;",
"%s",
"invalid uuid",
"%s/.1",
"%s/.1/%s",
"init",
"()V",
"a",
"()V",
"b",
"(Ljava/lang/String;)V",
"postJson",
"(Ljava/lang/String;Lorg/json/JSONObject;)I",
"%ld",
"content",
"time",
"sign",
"com/baidu/protect/B",
"addItem",
"(Lorg/json/JSONObject;Ljava/lang/String;Ljava/lang/String;)Lorg/json/JSONObject;",
"UUID",
"com/baidu/protect/B",
"addBasicItem",
"(Lorg/json/JSONObject;)Lorg/json/JSONObject;",
"VERSION",
"%s",
"%d",
"JS",
"%s",
"SDIR",
"%s",
"DDIR",
"%d",
"DC",
"%d",
"EM",
"%s",
"ABI",
"%d",
"SIG",
"%ld",
"jnionload",
"%ld",
"oncreate",
"emsg",
"emsg",
"STATE",
"com/baidu/protect/B",
"dumpJSONObject",
"(Lorg/json/JSONObject;)Ljava/lang/String;",
"com/baidu/protect/B",
"addItem",
"(Lorg/json/JSONObject;Ljava/lang/String;I)Lorg/json/JSONObject;",
"FINGERPRINT",
"generic",
"unknown",
"android/os/Build",
"MODEL",
"google_sdk",
"Emulator",
"Android SDK built for x86",
"Ljava/lang/String;",
"%s.lock",
"%s",
"FeatureSecuritySDK",
"com/baidu/xshield/ac/XH",
"(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;[I)V",
"init",
"(ILjava/lang/Object;[Ljava/lang/Object;)V",
"(ILjava/lang/Object;[Ljava/lang/Object;)Z",
"(ILjava/lang/Object;[Ljava/lang/Object;)B",
"(ILjava/lang/Object;[Ljava/lang/Object;)C",
"(ILjava/lang/Object;[Ljava/lang/Object;)S",
"(ILjava/lang/Object;[Ljava/lang/Object;)I",
"(ILjava/lang/Object;[Ljava/lang/Object;)J",
"(ILjava/lang/Object;[Ljava/lang/Object;)F",
"(ILjava/lang/Object;[Ljava/lang/Object;)D",
"(ILjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;",
"V",
"Z",
"B",
"C",
"S",
"I",
"J",
"F",
"D",
"L",
"FeatureVMProtection",
"Allocate registerMap failed.",
"",
"divide by zero",
"divide by zero",
"divide by zero",
"divide by zero",
"divide by zero",
"divide by zero",
"bad filled array req",
"filled-new-array not implemented for anything but 'int'",
"Allocate contents failed.",
"<init>",
"Allocate memory failed.",
"Allocate memory failed.",
"[F",
"[D",
"java/lang/Boolean",
"java/lang/Byte",
"java/lang/Character",
"java/lang/Short",
"java/lang/Integer",
"java/lang/Long",
"java/lang/Float",
"java/lang/Double",
"java/lang/Object",
"<init>",
"(Z)V",
"<init>",
"(B)V",
"<init>",
"(C)V",
"<init>",
"(S)V",
"<init>",
"(I)V",
"<init>",
"(J)V",
"<init>",
"(F)V",
"<init>",
"(D)V",
"booleanValue",
"()Z",
"byteValue",
"()B",
"charValue",
"()C",
"shortValue",
"()S",
"intValue",
"()I",
"longValue",
"()J",
"floatValue",
"()F",
"doubleValue",
"()D",
"java/lang/String",
"intern",
"()Ljava/lang/String;",
"java/lang/NullPointerException",
"length=%d; index=%d",
"java/lang/ArrayIndexOutOfBoundsException",
"java/lang/ArithmeticException",
"java/lang/NoSuchMethodError",
"java/lang/AbstractMethodError",
"java/lang/NoSuchFieldError",
"java/lang/IncompatibleClassChangeError",
"java/lang/ClassCastException",
"%d",
"java/lang/NegativeArraySizeException",
"java/lang/RuntimeException",
"java/lang/InternalError",
"java/lang/OutOfMemoryError",

]

def get_string(addr):
    out = ""
    while True:
        if get_byte(addr) != 0:
            out += chr(get_byte(addr))
        else:
            break
        addr += 1
    return out

addr = rodata_start_addr
index = 0

while addr < rodata_end_addr:
    str_encode = get_string(addr)
    str_len = len(str_encode) + 1
    if all(c in string.hexdigits for c in str_encode) and str_len > 8:
        i = 0
        tmp_addr = addr
        decrypted_strlen = len(decrypted_str[index])

        while i < str_len:
            if i >= decrypted_strlen:
                patch_byte(tmp_addr, 0x00)
            else:
                patch_byte(tmp_addr, ord(decrypted_str[index][i]))
            i = i + 1
            tmp_addr = tmp_addr + 1
        index = index + 1
    addr += str_len
